---
title: "Kody z zajęć"
author: "Łukasz Wawrowski"
date: "17-11-2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## przetwarzanie

```{r eval=FALSE}
library(tidyverse)

filmy <- read_csv("data/movies.csv")

# zadanie
filmy %>% 
  summarise(sr_czas=mean(duration),
            med_czas=median(duration),
            odch_czas=sd(duration))

genre_duration <- filmy %>% 
  group_by(genre) %>% 
  summarise(sr_czas=mean(duration),
            liczba_filmow=n())

# zliczanie
filmy %>%
  count(genre)

filmy %>% 
  group_by(genre) %>% 
  summarise(n=n())

director_genre <- filmy %>%
  count(director, genre)

# zadanie
dir_year <- filmy %>%
  filter(year >= 2000, year <= 2010) %>% 
  group_by(year) %>% 
  summarise(srednia_ocena=mean(rating),
            liczba=n()) %>% 
  arrange(desc(liczba))

# łączenie danych

load("data/gus.RData")

przyrost16_17 <- left_join(x = przyrost2016,
                           y = przyrost2017)

przyrost16_17r <- right_join(x = przyrost2016,
                             y = przyrost2017,
                             by = c("id"="id", "name"))

przyrost15_17 <- inner_join(x = przyrost2015,
                            y = przyrost2017)

przyrost151617 <- full_join(x = przyrost2015,
                            y = full_join(x = przyrost2016,
                                          y = przyrost2017))

przyrost151617 <- full_join(x = przyrost2015, y = przyrost2016) %>% 
  full_join(x = ., y = przyrost2017)

# zadanie
dane_gus <- inner_join(x = bezrobocie,
                       y = pod_10tys,
                       by = c("id_powiat"="pow")) %>%
  mutate(pow=as.numeric(id_powiat)) %>%
  inner_join(x = ., y = wyn) %>% 
  select(-pow)

# szeroka i wąska reprezentacja danych
dane_gus %>%
  summarise(srednia_bezr=mean(stopa_bezr),
            srednia_pod10tys=mean(pod_10tys),
            srednia_wynagr=mean(wynagrodzenie))

dane_gus_long <- dane_gus %>%
  pivot_longer(stopa_bezr:wynagrodzenie)

dane_gus_long %>%
  group_by(name) %>%
  summarise(srednia=mean(value))

dane_gus_wide <- dane_gus_long %>%
  pivot_wider()

# przykład z reżyserem i gatunkiem
director_genre <- filmy %>%
  count(director, genre)

dir_genre_wide <- director_genre %>%
  pivot_wider(names_from = genre, values_from = n)

```


## wizualizacja

```{r eval=FALSE}
library(tidyverse)
library(readxl)

rossmann <- read_excel("data/rossmann.xlsx")

sklep <- rossmann %>% 
  filter(sklep_id == 7, czy_otwarty == "Tak")

plot(sklep$sprzedaz)
plot(sklep$sprzedaz, sklep$liczba_klientow)

hist(sklep$sprzedaz)

ggplot(data = sklep, aes(x = sprzedaz, 
                         y = liczba_klientow)) +
  geom_point() +
  xlab("Sprzedaż") +
  ylab("Liczba klientów") +
  xlim(0,18000) +
  ylim(0,1600) +
  ggtitle("Sprzedaż i liczba klientów w sklepie 7") +
  theme_light()

```

